services:
  db:
    image: postgres:15
    container_name: mike-db
    environment:
      POSTGRES_DB: mike-docker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5421:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mike-docker"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge