services:
  db:
    image: postgres:15
    container_name: mike-db
    environment:
      POSTGRES_DB: mike-local-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5411:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mike-local-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge